api_platform:
    title: 'Symfony-Angular Starter'
    description: 'Starter project for Symfony RESTful API and Angular SPA.'
    version: '1.0.0'
    enable_swagger_ui: false
    formats:
        jsonld:
            mime_types: ['application/ld+json']
        json:
            mime_types: ['application/json']
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    swagger:
         api_keys:
             apiKey:
                name: Authorization
                type: header
    eager_loading:
        force_eager: false
