framework:
    cache:
        # Put the unique name of your app here: the prefix seed
        # is used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The app cache caches to the filesystem by default.
        # Other options include:

        # Redis
        #app: cache.adapter.redis
        #default_redis_provider: redis://localhost

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu
    csrf_protection:
        enabled: true
    default_locale: en
    form: ~
    fragments: ~
    http_method_override: true
    php_errors:
        log: true
    request:
        formats:
            xml: 'application/xml; charset=UTF-8'
            csv: 'text/csv'
    router:
        strict_requirements: true
    secret: '%env(APP_SECRET)%'
    session:
        cookie_httponly: true
        cookie_lifetime: 0
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        name: session
    templating:
        engines:
            - twig
    translator:
        enabled: true
        fallbacks:
            - en
    validation:
        enabled: true
        enable_annotations: true
        strict_email: true
